force-app/main/default/objects/MZ_Coordinate__c/MZ_Coordinate__c.object-meta.xml
<CustomObject>
    <label>コーデ</label>
    <nameField>
        <displayFormat>CD-{0000}</displayFormat>
        <label>コーデID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>コーデ</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MZ_Coordinate__c/fields/MZ_CoordinateScore__c.field-meta.xml
<CustomField>
    <fullName>MZ_CoordinateScore__c</fullName>
    <label>コーデスコア</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CoordinateComparator.cls
public class CoordinateComparator implements Comparator<MZ_Coordinate__c> {
    public Integer compare(MZ_Coordinate__c c1, MZ_Coordinate__c c2) {
     	Integer returnValue = 0;
        if(c1 == null && c2 == null) {
            returnValue = 0;
        } else if(c1 == null) {
            returnValue = 1;
        } else if(c2 == null) {
            returnValue = -1;
        } else if(c1.MZ_CoordinateScore__c > c2.MZ_CoordinateScore__c) {
            returnValue = -1;
        } else if(c1.MZ_CoordinateScore__c < c2.MZ_CoordinateScore__c) {
        	returnValue = 1;
        }
        return returnValue;
    }
}