force-app/main/default/objects/MZ_Color__c/MZ_Color__c.object-meta.xml
<CustomObject>
    <label>カラー</label>
    <nameField>
        <label>カラー名</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>カラー</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MZ_Color__c/fields/MZ_ColorGroup__c.field-meta.xml
<CustomField>
    <fullName>MZ_ColorGroup__c</fullName>
    <label>カラーグループ</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MZ_ColorGroup</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MZ_Color__c/fields/MZ_ColorType__c.field-meta.xml
<CustomField>
    <fullName>MZ_ColorType__c</fullName>
    <label>カラー区分</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MZ_ColorType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MZ_Design__c/MZ_Design__c.object-meta.xml
<CustomObject>
    <label>デザイン</label>
    <nameField>
        <label>デザイン名</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>デザイン</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MZ_Design__c/fields/MZ_DesignType__c.field-meta.xml
<CustomField>
    <fullName>MZ_DesignType__c</fullName>
    <label>デザイン区分</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MZ_DesignType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MZ_Item__c/MZ_Item__c.object-meta.xml
<CustomObject>
    <label>アイテム</label>
    <nameField>
        <label>アイテム名</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>アイテム</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MZ_Item__c/fields/MZ_Category__c.field-meta.xml
<CustomField>
    <fullName>MZ_Category__c</fullName>
    <label>カテゴリ</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MZ_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MZ_Item__c/fields/MZ_Color__c.field-meta.xml
<CustomField>
    <fullName>MZ_Color__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>カラー</label>
    <referenceTo>MZ_Color__c</referenceTo>
    <relationshipLabel>アイテム</relationshipLabel>
    <relationshipName>MZ_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MZ_Item__c/fields/MZ_ContentBodyId__c.field-meta.xml
<CustomField>
    <fullName>MZ_ContentBodyId__c</fullName>
    <label>コンテンツボディID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MZ_Item__c/fields/MZ_ContentVersionId__c.field-meta.xml
<CustomField>
    <fullName>MZ_ContentVersionId__c</fullName>
    <label>コンテンツバージョンID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MZ_Item__c/fields/MZ_Design__c.field-meta.xml
<CustomField>
    <fullName>MZ_Design__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>デザイン</label>
    <referenceTo>MZ_Design__c</referenceTo>
    <relationshipLabel>アイテム</relationshipLabel>
    <relationshipName>MZ_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MZ_Item__c/fields/MZ_ImageFileExtension__c.field-meta.xml
<CustomField>
    <fullName>MZ_ImageFileExtension__c</fullName>
    <label>画像ファイル拡張子</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MZ_Item__c/fields/MZ_Season__c.field-meta.xml
<CustomField>
    <fullName>MZ_Season__c</fullName>
    <label>シーズン</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MZ_Season</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MZ_Item__c/fields/MZ_Style__c.field-meta.xml
<CustomField>
    <fullName>MZ_Style__c</fullName>
    <label>スタイル</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MZ_Style</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MZ_Item__c/fields/MZ_SubCategory__c.field-meta.xml
<CustomField>
    <fullName>MZ_SubCategory__c</fullName>
    <label>サブカテゴリ</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MZ_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>MZ_SubCategory</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MZ_Item__c/recordTypes/MZ_Outer_RecordType.recordType-meta.xml
<RecordType>
    <fullName>MZ_Outer_RecordType</fullName>
    <active>true</active>
    <label>01_アウター</label>
</RecordType>

force-app/main/default/globalValueSets/MZ_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>アウター</fullName>
    </customValue>
    <customValue>
        <fullName>トップス</fullName>
    </customValue>
    <customValue>
        <fullName>パンツ</fullName>
    </customValue>
    <customValue>
        <fullName>スカート</fullName>
    </customValue>
    <customValue>
        <fullName>ワンピース</fullName>
    </customValue>
    <customValue>
        <fullName>バッグ</fullName>
    </customValue>
    <customValue>
        <fullName>シューズ</fullName>
    </customValue>
    <customValue>
        <fullName>その他アイテム</fullName>
    </customValue>
    <masterLabel>カテゴリ</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/MZ_ColorGroup.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ホワイト</fullName>
    </customValue>
    <customValue>
        <fullName>ブラック</fullName>
    </customValue>
    <customValue>
        <fullName>グレー</fullName>
    </customValue>
    <customValue>
        <fullName>ブラウン</fullName>
    </customValue>
    <customValue>
        <fullName>ベージュ</fullName>
    </customValue>
    <customValue>
        <fullName>グリーン</fullName>
    </customValue>
    <customValue>
        <fullName>ブルー</fullName>
    </customValue>
    <customValue>
        <fullName>パープル</fullName>
    </customValue>
    <customValue>
        <fullName>イエロー</fullName>
    </customValue>
    <customValue>
        <fullName>ピンク</fullName>
    </customValue>
    <customValue>
        <fullName>レッド</fullName>
    </customValue>
    <customValue>
        <fullName>オレンジ</fullName>
    </customValue>
    <customValue>
        <fullName>その他カラー</fullName>
    </customValue>
    <masterLabel>カラーグループ</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/MZ_ColorType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ベース</fullName>
    </customValue>
    <customValue>
        <fullName>アクセント</fullName>
    </customValue>
    <masterLabel>カラー区分</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/MZ_DesignType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>無地</fullName>
    </customValue>
    <customValue>
        <fullName>デザイン</fullName>
    </customValue>
    <masterLabel>デザイン区分</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/MZ_Season.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>春</fullName>
    </customValue>
    <customValue>
        <fullName>夏</fullName>
    </customValue>
    <customValue>
        <fullName>秋</fullName>
    </customValue>
    <customValue>
        <fullName>冬</fullName>
    </customValue>
    <masterLabel>シーズン</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/MZ_Style.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>フォーマル</fullName>
    </customValue>
    <customValue>
        <fullName>カジュアル</fullName>
    </customValue>
    <masterLabel>系統</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/MZ_SubCategory.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>チェスターコート</fullName>
    </customValue>
    <customValue>
        <fullName>ピーコート</fullName>
    </customValue>
    <customValue>
        <fullName>ダッフルコート</fullName>
    </customValue>
    <customValue>
        <fullName>モッズコート</fullName>
    </customValue>
    <customValue>
        <fullName>トレンチコート</fullName>
    </customValue>
    <customValue>
        <fullName>ステンカラーコート</fullName>
    </customValue>
    <customValue>
        <fullName>ダウンジャケット</fullName>
    </customValue>
    <customValue>
        <fullName>テーラードジャケット</fullName>
    </customValue>
    <customValue>
        <fullName>ライダースジャケット</fullName>
    </customValue>
    <customValue>
        <fullName>ミリタリージャケット</fullName>
    </customValue>
    <customValue>
        <fullName>デニムジャケット</fullName>
    </customValue>
    <customValue>
        <fullName>カバーオール</fullName>
    </customValue>
    <customValue>
        <fullName>ブルゾン</fullName>
    </customValue>
    <customValue>
        <fullName>スタジャン</fullName>
    </customValue>
    <customValue>
        <fullName>マウンテンパーカー</fullName>
    </customValue>
    <customValue>
        <fullName>ダウンベスト</fullName>
    </customValue>
    <customValue>
        <fullName>その他アウター</fullName>
    </customValue>
    <customValue>
        <fullName>ニット</fullName>
    </customValue>
    <customValue>
        <fullName>カーディガン</fullName>
    </customValue>
    <customValue>
        <fullName>ベスト</fullName>
    </customValue>
    <customValue>
        <fullName>アンサンブル</fullName>
    </customValue>
    <customValue>
        <fullName>パーカー</fullName>
    </customValue>
    <customValue>
        <fullName>スウェット</fullName>
    </customValue>
    <customValue>
        <fullName>チュニック</fullName>
    </customValue>
    <customValue>
        <fullName>シャツ・ブラウス</fullName>
    </customValue>
    <customValue>
        <fullName>ポロシャツ</fullName>
    </customValue>
    <customValue>
        <fullName>Tシャツ・カットソー</fullName>
    </customValue>
    <customValue>
        <fullName>タンクトップ</fullName>
    </customValue>
    <customValue>
        <fullName>その他トップス</fullName>
    </customValue>
    <customValue>
        <fullName>パンツ</fullName>
    </customValue>
    <masterLabel>サブカテゴリ</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContentDocumentLinkTriggerHandlerTest.cls
@isTest
private class ContentDocumentLinkTriggerHandlerTest {
    @TestSetup
    static void setupTestData() {
        // Colorレコード、Designレコードを作成
        insert new MZ_Color__c(Name = 'テストカラー', MZ_ColorType__c = 'ベース', MZ_ColorGroup__c = 'その他カラー');
        insert new MZ_Design__c(Name = 'テストデザイン', MZ_DesignType__c = '無地');
        
        // Itemレコードを作成
        MZ_Item__c item = new MZ_Item__c();
        RecordType rt = [select Id from RecordType where DeveloperName = 'MZ_Outer_RecordType' limit 1];
        MZ_Color__c color = [select Id from MZ_Color__c where Name = 'テストカラー' limit 1];
        MZ_Design__c design = [select Id from MZ_Design__c where Name = 'テストデザイン' limit 1];
        item.Name = 'テストアウター';
        item.RecordTypeId = rt.Id;
        item.MZ_Category__c = 'アウター';
        item.MZ_SubCategory__c = 'その他アウター';
        item.MZ_Color__c = color.Id;
        item.MZ_Design__c = design.Id;
        item.MZ_Season__c = '冬';
        item.MZ_Style__c = 'フォーマル';
        insert item;
        
        // ContentVersionレコード（ダミー画像）を作成
        List<ContentVersion> cvList = new List<ContentVersion>();
        for(integer i = 1; i <= 2; i++) {
            ContentVersion cv = new ContentVersion();
            cv.Title = 'テストイメージ' + i;
            cv.PathOnClient = i == 1 ? 'test1.jpg' : 'test2.png';
            cv.VersionData = Blob.valueOf('test' + i); // 文字列からダミー画像（BLOG型）を生成
            cvList.add(cv);
        }
        
        insert cvList;
    }
   
    @isTest
    static void testInsertAndDelete() {
        // テストItemレコード、ContentVersionレコードを取得
        MZ_Item__c item = [select Id, MZ_ContentVersionId__c, MZ_ContentBodyId__c, MZ_ImageFileExtension__c from MZ_Item__c where Name = 'テストアウター' limit 1];
        ContentVersion cv1 = [select Id, ContentDocumentId, ContentBodyId, FileExtension from ContentVersion where Title = 'テストイメージ1' limit 1];
        ContentVersion cv2 = [select Id, ContentDocumentId, ContentBodyId, FileExtension from ContentVersion where Title = 'テストイメージ2' limit 1];
        
        // ContentDocumentLinkレコードを新規作成
        ContentDocumentLink cdl1 = new ContentDocumentLink(LinkedEntityId = item.Id, ContentDocumentId = cv1.ContentDocumentId);
        insert cdl1;
        
        // 結果テスト
        MZ_Item__c updatedItem1 = [select MZ_ContentVersionId__c, MZ_ContentBodyId__c, MZ_ImageFileExtension__c from MZ_Item__c where Name = 'テストアウター' limit 1];
        System.assertEquals(cv1.Id, updatedItem1.MZ_ContentVersionId__c, 'ContentVersionId is not correct.');
        System.assertEquals(cv1.ContentBodyId, updatedItem1.MZ_ContentBodyId__c, 'ContentBodyId is not correct.');
        System.assertEquals('jpg', updatedItem1.MZ_ImageFileExtension__c, 'ImageFileExtension is not correct.');

        // ContentDocumentLinkレコードを追加作成
        ContentDocumentLink cdl2 = new ContentDocumentLink(LinkedEntityId = item.Id, ContentDocumentId = cv2.ContentDocumentId);
        insert cdl2;
        
        // 結果テスト（対象外）
        MZ_Item__c updatedItem2 = [select MZ_ContentVersionId__c, MZ_ContentBodyId__c, MZ_ImageFileExtension__c from MZ_Item__c where Name = 'テストアウター' limit 1];
        System.assertEquals(cv2.Id, updatedItem2.MZ_ContentVersionId__c, 'ContentVersionId is not correct.');
        System.assertEquals(cv2.ContentBodyId, updatedItem2.MZ_ContentBodyId__c, 'ContentBodyId is not correct.');
        System.assertEquals('png', updatedItem2.MZ_ImageFileExtension__c, 'ImageFileExtension is not correct.');

        
        // ContentDocumentLinkレコードを削除（関連ファイル残）
        delete cdl2;
        // 結果テスト
        MZ_Item__c deletedItem1 = [select MZ_ContentVersionId__c, MZ_ContentBodyId__c, MZ_ImageFileExtension__c from MZ_Item__c where Name = 'テストアウター' limit 1];
        System.assertEquals(cv1.Id, deletedItem1.MZ_ContentVersionId__c, 'ContentVersionId is not correct.');
        System.assertEquals(cv1.ContentBodyId, deletedItem1.MZ_ContentBodyId__c, 'ContentBodyId is not correct.');
        System.assertEquals('jpg', deletedItem1.MZ_ImageFileExtension__c, 'ImageFileExtension is not correct.');
        
        // ContentDocumentLinkレコードを削除（関連ファイル無）
        delete cdl1;
        // 結果テスト
        MZ_Item__c deletedItem2 = [select MZ_ContentVersionId__c, MZ_ContentBodyId__c, MZ_ImageFileExtension__c from MZ_Item__c where Name = 'テストアウター' limit 1];
        System.assert(deletedItem2.MZ_ContentVersionId__c == null, 'ContentVersionId is not null.');
        System.assert(deletedItem2.MZ_ContentBodyId__c == null, 'ContentBodyId is not null.');
        System.assert(deletedItem2.MZ_ImageFileExtension__c == null, 'ImageFileExtension is not null.');    
    }
}