force-app/main/default/objects/MZ_Color__c/MZ_Color__c.object-meta.xml
<CustomObject>
    <label>カラー</label>
    <nameField>
        <label>カラー名</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>カラー</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MZ_Color__c/fields/MZ_ColorGroup__c.field-meta.xml
<CustomField>
    <fullName>MZ_ColorGroup__c</fullName>
    <label>カラーグループ</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MZ_ColorGroup</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MZ_Color__c/fields/MZ_ColorType__c.field-meta.xml
<CustomField>
    <fullName>MZ_ColorType__c</fullName>
    <label>カラー区分</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MZ_ColorType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MZ_ColorMatching__c/MZ_ColorMatching__c.object-meta.xml
<CustomObject>
    <label>カラーマッチング</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>カラーマッチングID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>カラーマッチング</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MZ_ColorMatching__c/fields/MZ_Color1__c.field-meta.xml
<CustomField>
    <fullName>MZ_Color1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>カラー1</label>
    <referenceTo>MZ_Color__c</referenceTo>
    <relationshipLabel>カラーマッチング（カラー1）</relationshipLabel>
    <relationshipName>MZ_ColorMatchings1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MZ_ColorMatching__c/fields/MZ_Color2__c.field-meta.xml
<CustomField>
    <fullName>MZ_Color2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>カラー2</label>
    <referenceTo>MZ_Color__c</referenceTo>
    <relationshipLabel>カラーマッチング (カラー2)</relationshipLabel>
    <relationshipName>MZ_ColorMatchings2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MZ_ColorMatching__c/fields/MZ_MatchingScore__c.field-meta.xml
<CustomField>
    <fullName>MZ_MatchingScore__c</fullName>
    <label>マッチングスコア</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MZ_Coordinate__c/MZ_Coordinate__c.object-meta.xml
<CustomObject>
    <label>コーデ</label>
    <nameField>
        <displayFormat>CD-{0000}</displayFormat>
        <label>コーデID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>コーデ</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MZ_Coordinate__c/fields/MZ_Bottoms__c.field-meta.xml
<CustomField>
    <fullName>MZ_Bottoms__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ボトムス</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>MZ_Item__c.MZ_Category__c</field>
            <operation>equals</operation>
            <value>パンツ, スカート, ワンピース</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>MZ_Item__c</referenceTo>
    <relationshipLabel>コーデ (ボトムス)</relationshipLabel>
    <relationshipName>MZ_Coordinates_Bottoms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MZ_Coordinate__c/fields/MZ_CoordinateScore__c.field-meta.xml
<CustomField>
    <fullName>MZ_CoordinateScore__c</fullName>
    <label>コーデスコア</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MZ_Coordinate__c/fields/MZ_Inner__c.field-meta.xml
<CustomField>
    <fullName>MZ_Inner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>インナー</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>MZ_Item__c.MZ_SubCategory__c</field>
            <operation>equals</operation>
            <value>チュニック, シャツ・ブラウス, ポロシャツ, Tシャツ・カットソー, タンクトップ</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>MZ_Item__c</referenceTo>
    <relationshipLabel>コーデ (インナー)</relationshipLabel>
    <relationshipName>MZ_Coordinates_Inner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MZ_Coordinate__c/fields/MZ_Outer__c.field-meta.xml
<CustomField>
    <fullName>MZ_Outer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>アウター</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>MZ_Item__c.MZ_Category__c</field>
            <operation>equals</operation>
            <value>アウター</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>MZ_Item__c</referenceTo>
    <relationshipLabel>コーデ（アウター）</relationshipLabel>
    <relationshipName>MZ_Coordinates_Outer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MZ_Coordinate__c/fields/MZ_Season__c.field-meta.xml
<CustomField>
    <fullName>MZ_Season__c</fullName>
    <label>シーズン</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MZ_Season</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MZ_Coordinate__c/fields/MZ_Shoes__c.field-meta.xml
<CustomField>
    <fullName>MZ_Shoes__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>シューズ</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>MZ_Item__c.MZ_Category__c</field>
            <operation>equals</operation>
            <value>シューズ</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>MZ_Item__c</referenceTo>
    <relationshipLabel>コーデ (シューズ)</relationshipLabel>
    <relationshipName>MZ_Coordinates_Shoes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MZ_Coordinate__c/fields/MZ_Tops__c.field-meta.xml
<CustomField>
    <fullName>MZ_Tops__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>トップス</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>MZ_Item__c.MZ_Category__c</field>
            <operation>equals</operation>
            <value>トップス</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>MZ_Item__c</referenceTo>
    <relationshipLabel>コーデ (トップス)</relationshipLabel>
    <relationshipName>MZ_Coordinates_Tops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MZ_Design__c/MZ_Design__c.object-meta.xml
<CustomObject>
    <label>デザイン</label>
    <nameField>
        <label>デザイン名</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>デザイン</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MZ_Design__c/fields/MZ_DesignType__c.field-meta.xml
<CustomField>
    <fullName>MZ_DesignType__c</fullName>
    <label>デザイン区分</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MZ_DesignType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MZ_Item__c/MZ_Item__c.object-meta.xml
<CustomObject>
    <label>アイテム</label>
    <nameField>
        <label>アイテム名</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>アイテム</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MZ_Item__c/fields/MZ_Category__c.field-meta.xml
<CustomField>
    <fullName>MZ_Category__c</fullName>
    <label>カテゴリ</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MZ_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MZ_Item__c/fields/MZ_Color__c.field-meta.xml
<CustomField>
    <fullName>MZ_Color__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>カラー</label>
    <referenceTo>MZ_Color__c</referenceTo>
    <relationshipLabel>アイテム</relationshipLabel>
    <relationshipName>MZ_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MZ_Item__c/fields/MZ_Design__c.field-meta.xml
<CustomField>
    <fullName>MZ_Design__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>デザイン</label>
    <referenceTo>MZ_Design__c</referenceTo>
    <relationshipLabel>アイテム</relationshipLabel>
    <relationshipName>MZ_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MZ_Item__c/fields/MZ_ItemImage__c.field-meta.xml
<CustomField>
    <fullName>MZ_ItemImage__c</fullName>
    <formula>IF(
NOT( ISBLANK( MZ_ContentVersionId__c )), 
IMAGE(&quot;https://wise-goat-7438ot-dev-ed.trailblaze.file.force.com/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_&quot;&amp;
  CASE( MZ_ImageFileExtension__c, &quot;jpg&quot;, &quot;Jpg&quot;, &quot;jpeg&quot;, &quot;Jpeg&quot;, &quot;png&quot;, &quot;Png&quot;, &quot;&quot;)&amp;
  &quot;&amp;versionId=&quot;&amp; MZ_ContentVersionId__c &amp;&quot;&amp;operationContext=CHATTER&amp;contentId=&quot;&amp; MZ_ContentBodyId__c , &quot;&quot;),
NULL
)</formula>
    <label>アイテム画像</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MZ_Item__c/fields/MZ_ItemURL__c.field-meta.xml
<CustomField>
    <fullName>MZ_ItemURL__c</fullName>
    <formula>IF(
NOT( ISBLANK( MZ_ContentVersionId__c )), 
&quot;/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_&quot;&amp;
  CASE( MZ_ImageFileExtension__c, &quot;jpg&quot;, &quot;Jpg&quot;, &quot;jpeg&quot;, &quot;Jpeg&quot;, &quot;png&quot;, &quot;Png&quot;, &quot;&quot;)&amp;
  &quot;&amp;versionId=&quot;&amp; MZ_ContentVersionId__c &amp;&quot;&amp;operationContext=CHATTER&amp;contentId=&quot;&amp; MZ_ContentBodyId__c,
NULL
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>アイテムURL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MZ_Item__c/fields/MZ_PurchaseDate__c.field-meta.xml
<CustomField>
    <fullName>MZ_PurchaseDate__c</fullName>
    <label>購入年月日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MZ_Item__c/fields/MZ_PurchasePrice__c.field-meta.xml
<CustomField>
    <fullName>MZ_PurchasePrice__c</fullName>
    <label>購入価格</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MZ_Item__c/fields/MZ_PurchaseShop__c.field-meta.xml
<CustomField>
    <fullName>MZ_PurchaseShop__c</fullName>
    <label>購入ショップ</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MZ_Item__c/fields/MZ_Season__c.field-meta.xml
<CustomField>
    <fullName>MZ_Season__c</fullName>
    <label>シーズン</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MZ_Season</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MZ_Item__c/fields/MZ_Style__c.field-meta.xml
<CustomField>
    <fullName>MZ_Style__c</fullName>
    <label>スタイル</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MZ_Style</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MZ_Item__c/fields/MZ_SubCategory__c.field-meta.xml
<CustomField>
    <fullName>MZ_SubCategory__c</fullName>
    <label>サブカテゴリ</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MZ_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>MZ_SubCategory</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/MZ_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>アウター</fullName>
    </customValue>
    <customValue>
        <fullName>トップス</fullName>
    </customValue>
    <customValue>
        <fullName>パンツ</fullName>
    </customValue>
    <customValue>
        <fullName>スカート</fullName>
    </customValue>
    <customValue>
        <fullName>ワンピース</fullName>
    </customValue>
    <customValue>
        <fullName>バッグ</fullName>
    </customValue>
    <customValue>
        <fullName>シューズ</fullName>
    </customValue>
    <customValue>
        <fullName>その他アイテム</fullName>
    </customValue>
    <masterLabel>カテゴリ</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/MZ_ColorGroup.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ホワイト</fullName>
    </customValue>
    <customValue>
        <fullName>ブラック</fullName>
    </customValue>
    <customValue>
        <fullName>グレー</fullName>
    </customValue>
    <customValue>
        <fullName>ブラウン</fullName>
    </customValue>
    <customValue>
        <fullName>ベージュ</fullName>
    </customValue>
    <customValue>
        <fullName>グリーン</fullName>
    </customValue>
    <customValue>
        <fullName>ブルー</fullName>
    </customValue>
    <customValue>
        <fullName>パープル</fullName>
    </customValue>
    <customValue>
        <fullName>イエロー</fullName>
    </customValue>
    <customValue>
        <fullName>ピンク</fullName>
    </customValue>
    <customValue>
        <fullName>レッド</fullName>
    </customValue>
    <customValue>
        <fullName>オレンジ</fullName>
    </customValue>
    <customValue>
        <fullName>その他カラー</fullName>
    </customValue>
    <masterLabel>カラーグループ</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/MZ_ColorType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ベース</fullName>
    </customValue>
    <customValue>
        <fullName>アクセント</fullName>
    </customValue>
    <masterLabel>カラー区分</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/MZ_DesignType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>無地</fullName>
    </customValue>
    <customValue>
        <fullName>デザイン</fullName>
    </customValue>
    <masterLabel>デザイン区分</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/MZ_Season.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>春</fullName>
    </customValue>
    <customValue>
        <fullName>夏</fullName>
    </customValue>
    <customValue>
        <fullName>秋</fullName>
    </customValue>
    <customValue>
        <fullName>冬</fullName>
    </customValue>
    <masterLabel>シーズン</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/MZ_Style.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>フォーマル</fullName>
    </customValue>
    <customValue>
        <fullName>カジュアル</fullName>
    </customValue>
    <masterLabel>系統</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/MZ_SubCategory.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>チェスターコート</fullName>
    </customValue>
    <customValue>
        <fullName>ピーコート</fullName>
    </customValue>
    <customValue>
        <fullName>ダッフルコート</fullName>
    </customValue>
    <customValue>
        <fullName>モッズコート</fullName>
    </customValue>
    <customValue>
        <fullName>トレンチコート</fullName>
    </customValue>
    <customValue>
        <fullName>ステンカラーコート</fullName>
    </customValue>
    <customValue>
        <fullName>ダウンジャケット</fullName>
    </customValue>
    <customValue>
        <fullName>テーラードジャケット</fullName>
    </customValue>
    <customValue>
        <fullName>ライダースジャケット</fullName>
    </customValue>
    <customValue>
        <fullName>ミリタリージャケット</fullName>
    </customValue>
    <customValue>
        <fullName>デニムジャケット</fullName>
    </customValue>
    <customValue>
        <fullName>カバーオール</fullName>
    </customValue>
    <customValue>
        <fullName>ブルゾン</fullName>
    </customValue>
    <customValue>
        <fullName>スタジャン</fullName>
    </customValue>
    <customValue>
        <fullName>マウンテンパーカー</fullName>
    </customValue>
    <customValue>
        <fullName>ダウンベスト</fullName>
    </customValue>
    <customValue>
        <fullName>その他アウター</fullName>
    </customValue>
    <customValue>
        <fullName>ニット</fullName>
    </customValue>
    <customValue>
        <fullName>カーディガン</fullName>
    </customValue>
    <customValue>
        <fullName>ベスト</fullName>
    </customValue>
    <customValue>
        <fullName>アンサンブル</fullName>
    </customValue>
    <customValue>
        <fullName>パーカー</fullName>
    </customValue>
    <customValue>
        <fullName>スウェット</fullName>
    </customValue>
    <customValue>
        <fullName>チュニック</fullName>
    </customValue>
    <customValue>
        <fullName>シャツ・ブラウス</fullName>
    </customValue>
    <customValue>
        <fullName>ポロシャツ</fullName>
    </customValue>
    <customValue>
        <fullName>Tシャツ・カットソー</fullName>
    </customValue>
    <customValue>
        <fullName>タンクトップ</fullName>
    </customValue>
    <customValue>
        <fullName>その他トップス</fullName>
    </customValue>
    <customValue>
        <fullName>パンツ</fullName>
    </customValue>
    <customValue>
        <fullName>スカート</fullName>
    </customValue>
    <masterLabel>サブカテゴリ</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ItemController.cls
public class ItemController {
    
    @AuraEnabled(cacheable=true)
    public static List<MZ_Item__c> getItems(String category, String subCategory, String colorGroup, 
                                            String designType, String season, String searchKey, 
                                            String sortKey, String sortOrder) {

        String query = 'SELECT Id, Name, MZ_Category__c, MZ_SubCategory__c, MZ_Color__r.MZ_ColorGroup__c, ';
        query += 'MZ_Design__r.MZ_DesignType__c, MZ_Season__c, MZ_ItemURL__c, MZ_ItemImage__c, ';
        query += 'MZ_PurchaseDate__c, MZ_PurchasePrice__c, MZ_PurchaseShop__c FROM MZ_Item__c ';
        
        // 条件用のリストを定義
        List<String> conditions = new List<String>();
        // バインド変数を定義
        Map<String, Object> binds = new Map<String, Object>();
        
        if (String.isNotBlank(category)) {
            System.debug('category: '+category);
            conditions.add('MZ_Category__c = :category');
            binds.put('category', category);
        }
        if (String.isNotBlank(subCategory)) {
            conditions.add('MZ_SubCategory__c = :subCategory');
            binds.put('subCategory', subCategory);
        }
        if (String.isNotBlank(colorGroup)) {
            conditions.add('MZ_Color__r.MZ_ColorGroup__c = :colorGroup');
            binds.put('colorGroup', colorGroup);
        }
        if (String.isNotBlank(designType)) {
            conditions.add('MZ_Design__r.MZ_DesignType__c = :designType');
            binds.put('designType', designType);
        }
        if (String.isNotBlank(season)) {
            conditions.add('MZ_Season__c INCLUDES (:season)');
            binds.put('season', season);
        }
        if (String.isNotBlank(searchKey)) {
            conditions.add('Name LIKE :searchKey');
            binds.put('searchKey', '%' + searchKey + '%');
        }
    
  		// 条件がある場合はWHERE句を追加
        if (!conditions.isEmpty()) {
            query += ' WHERE ' + String.join(conditions, ' AND ');
        }
                                                
        // ソートキー指定がある場合は指定
        if(String.isNotBlank(sortKey)) {
            query += ' ORDER BY ' + sortKey + ' ' + sortOrder;
        } else {
	        query += ' ORDER BY CreatedDate DESC';            
        }                                       
        System.debug('query: '+query);
		System.debug('binds: '+binds);
        return Database.queryWithBinds(query, binds, AccessLevel.USER_MODE);
	}
    
    @AuraEnabled(cacheable=true)
    public static List<MZ_Coordinate__c> generateCoordinates(Id recordId, String season) {
        // アウター、トップス、インナー、ボトムス、シューズのリスト格納用
        List<List<MZ_Item__c>> outerList = new List<List<MZ_Item__c>>();
        List<List<MZ_Item__c>> topsList = new List<List<MZ_Item__c>>();
        List<List<MZ_Item__c>> innerList = new List<List<MZ_Item__c>>();
        List<List<MZ_Item__c>> bottomsList = new List<List<MZ_Item__c>>();
        List<List<MZ_Item__c>> shoesList = new List<List<MZ_Item__c>>();
        
        // コーデリスト格納用
        List<List<MZ_Coordinate__c>> coordList = new List<List<MZ_Coordinate__c>>();
        List<MZ_Coordinate__c> recommendCoordList = new List<MZ_Coordinate__c>();
        
        // アウター、トップス、インナー、ボトムス、シューズのリスト取得
        List<MZ_Item__c> outers = [SELECT Id FROM MZ_Item__c WHERE MZ_Category__c = 'アウター' AND MZ_Season__c = :season];
        List<MZ_Item__c> outerTops = [SELECT Id FROM MZ_Item__c 
                                      WHERE MZ_SubCategory__c IN ('ニット', 'カーディガン', 'ベスト', 'アンサンブル', 'パーカー', 'スウェット', 'チュニック', 'その他トップス') 
                                      AND MZ_Season__c = :season];
        List<MZ_Item__c> innerTops = [SELECT Id FROM MZ_Item__c WHERE MZ_SubCategory__c IN ('シャツ・ブラウス', 'ポロシャツ') 
                                      AND MZ_Season__c = :season];
        List<MZ_Item__c> allTops = new List<MZ_Item__c>();
        allTops.addAll(outerTops);
        allTops.addAll(innerTops);
		List<MZ_Item__c> topsInners = [SELECT Id FROM MZ_Item__c WHERE MZ_SubCategory__c IN ('シャツ・ブラウス', 'Tシャツ・カットソー') AND MZ_Season__c = :season];
        List<MZ_Item__c> inners = [SELECT Id FROM MZ_Item__c WHERE MZ_SubCategory__c IN ('Tシャツ・カットソー', 'タンクトップ') AND MZ_Season__c = :season];
        List<MZ_Item__c> bottoms = [SELECT Id FROM MZ_Item__c WHERE MZ_Category__c IN ('パンツ', 'スカート') AND MZ_Season__c = :season];
        List<MZ_Item__c> shoes = [SELECT Id FROM MZ_Item__c WHERE MZ_Category__c = 'シューズ' AND MZ_Season__c = :season];
        
        // Idが存在する場合は該当カテゴリを固定アイテムにセット
        outers = setSelectedItem(recordId, outers);
       	outerTops = setSelectedItem(recordId, outerTops);
        innerTops = setSelectedItem(recordId, innerTops);
        allTops = setSelectedItem(recordId, allTops);
        topsInners = setSelectedItem(recordId, topsInners);
        inners = setSelectedItem(recordId, inners);
        bottoms = setSelectedItem(recordId, bottoms);
        shoes = setSelectedItem(recordId, shoes);
        
        // カラーマッチングテーブルを取得
        List<MZ_ColorMatching__c> colorMatchingTable = [SELECT Id, MZ_Color1__r.Id, MZ_Color2__r.Id, MZ_MatchingScore__c FROM MZ_ColorMatching__c];
        
        // シーズンに応じたコーデパターンをセット
        switch on season {
            when '春', '秋' {
                outerList.add(outers);
                outerList.add(Null);
                outerList.add(Null);
            	topsList.add(Null);
                topsList.add(outerTops);
                topsList.add(innerTops);
                innerList.add(topsInners);
                innerList.add(topsInners);
                innerList.add(inners);
                bottomsList.add(bottoms);
                bottomsList.add(bottoms);
                bottomsList.add(bottoms);
                shoesList.add(shoes);
                shoesList.add(shoes);
                shoesList.add(shoes);
            }
            when '夏' {
                outerList.add(outers);
                outerList.add(Null);
                outerList.add(Null);
            	topsList.add(Null);
                topsList.add(allTops);
                topsList.add(Null);
                innerList.add(inners);
                innerList.add(inners);
                innerList.add(inners);
                bottomsList.add(bottoms);
                bottomsList.add(bottoms);
                bottomsList.add(bottoms);
                shoesList.add(shoes);
                shoesList.add(shoes);
                shoesList.add(shoes);
            }
            when '冬' {
                outerList.add(outers);
                outerList.add(outers);
                topsList.add(outerTops);
                topsList.add(innerTops);
                innerList.add(topsInners);
                innerList.add(inners);
                bottomsList.add(bottoms);
                bottomsList.add(bottoms);
                shoesList.add(shoes);
                shoesList.add(shoes);
            }
            when else {
                System.debug('[ERROR] Season is not set.');
            }
        }
        
        // outerList[i]〜shoesList[i]（レコードリスト）からcoordList[i]（レコードリスト）を総当りで作成
        for(Integer i = 0; i < outerList.size(); i++) {
            List<MZ_Coordinate__c> coordinates = new List<MZ_Coordinate__c>();
            for(MZ_Item__c otrs : outerList[i]) {
                for(MZ_Item__c tps: topsList[i]) {
                    for(MZ_Item__c inrs: innerList[i]) {
                        for(MZ_Item__c btms: bottomsList[i]) {
                            for(MZ_Item__c shs: shoesList[i]) {
                                MZ_Coordinate__c coordinate = new MZ_Coordinate__c();
                                coordinate.MZ_Outer__r.Id = otrs.Id;
                                coordinate.MZ_Tops__r.Id = tps.Id;
                                coordinate.MZ_Inner__r.Id = inrs.Id;
                                coordinate.MZ_Bottoms__r.Id = btms.Id;
                                coordinate.MZ_Shoes__r.Id = shs.Id;
                                coordinate.MZ_CoordinateScore__c = calcCoordinateScore(coordinate, colorMatchingTable);
                                coordinates.add(coordinate);
                            }
                        }
                    }
                }            	
            }
            coordList.add(coordinates);
        }
        // コーデパターン毎にスコア順に並び替え、上位100件を取得
        for(Integer i = 0; i < outerList.size(); i++) {
            coordList[i].sort(new CoordinateComparator());
            for (Integer j = 0; j < 100 && j < coordList[i].size(); j++) {
                recommendCoordList.add(coordList[i][j]);
            }	
        }
        
		return recommendCoordList;                                                                                                         
    }
    
    // Idに一致するレコードがあれば固定値をセット
    static List<MZ_Item__c> setSelectedItem(Id recordId, List<MZ_Item__c> itemList) {
        for(MZ_Item__c item: itemList) {
            if(item.Id == recordId) {
                return new List<MZ_Item__c>{item};
            }
        }
        return itemList;
    }
    
    // コーデスコアを計算
    static Integer calcCoordinateScore(MZ_Coordinate__c coordinate, List<MZ_ColorMatching__c> colorMatchingTable) {
        Integer score = 0;
        Integer accentCnt = 0;
        Integer designCnt = 0;
        Integer formalCnt = 0;
        Integer casualCnt = 0;
        Decimal formalRate = 0;
        
        List<MZ_Item__c> itemList = new List<MZ_Item__c>{
            coordinate.MZ_Outer__r, 
            coordinate.MZ_Tops__r,
            coordinate.MZ_Inner__r,
            coordinate.MZ_Bottoms__r,
            coordinate.MZ_Shoes__r
        };
        
        // カラーマッチングテーブルに基づき各アイテムの組み合わせからスコアを算出
        for(MZ_ColorMatching__c cm: colorMatchingTable) {
            for(Integer i = 0; i < itemList.size(); i++) {
                for(Integer j = 0; j < itemList.size(); j++) {
                    if(i < j) {
                        if(itemList[i].MZ_Color__r.Id == cm.MZ_Color1__r.Id && itemList[j].MZ_Color__r.Id == cm.MZ_Color2__r.Id) {
                            score += Integer.valueOf(cm.MZ_MatchingScore__c);
                        } else if(itemList[i].MZ_Color__r.Id == cm.MZ_Color2__r.Id && itemList[j].MZ_Color__r.Id == cm.MZ_Color1__r.Id) {
                            score += Integer.valueOf(cm.MZ_MatchingScore__c);
                        } else {
                            System.debug('[ERROR] ColorMatching is not registered.');
                        }
                    }
                }
            }
        }
        
        // アクセントカラー、デザイン有無、フォーマル/カジュアル数を集計
        for(MZ_Item__c item: itemList) {
            if(item.MZ_Color__r.MZ_ColorType__c == 'アクセント') {
            	accentCnt += 1;
            }
            if(item.MZ_Design__r.MZ_DesignType__c == 'デザイン') {
                designCnt += 1;
            }
            if(item.MZ_Style__c == 'フォーマル') {
                formalCnt += 1;
            } else if (item.MZ_Style__c == 'カジュアル') {
                casualCnt += 1;
            }
        }
        
        // 集計値に応じてスコアを調整
        if(formalCnt + casualCnt > 0) {
            formalRate = formalCnt / (formalCnt + casualCnt);
        } else {
            formalRate = 0;
        }
        if(accentCnt == 1) {
            score += 3;
        } else if(accentCnt >= 2) {
            score -= 3;
        }
        if(designCnt == 1) {
            score += 3;
        } else if(designCnt >= 2) {
            score -= 3;
        }
        if(formalRate <= 0.5) {
            score -= 3;
        } else if(formalRate > 0.5 && formalRate <= 0.8) {
            score += 3;
        } else {
            score -= 3;
        }
        return score;
    }
}